// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"
	tourismpackages "erdmaze/businesses/tourism_packages"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, page, perpage
func (_m *Usecase) Fetch(ctx context.Context, page int, perpage int) ([]tourismpackages.Domain, int, int, error) {
	ret := _m.Called(ctx, page, perpage)

	var r0 []tourismpackages.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []tourismpackages.Domain); ok {
		r0 = rf(ctx, page, perpage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tourismpackages.Domain)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, perpage)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(context.Context, int, int) int); ok {
		r2 = rf(ctx, page, perpage)
	} else {
		r2 = ret.Get(2).(int)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, int, int) error); ok {
		r3 = rf(ctx, page, perpage)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetAll provides a mock function with given fields: ctx, tourismName, locationName, activityName
func (_m *Usecase) GetAll(ctx context.Context, tourismName string, locationName string, activityName string) ([]tourismpackages.Domain, error) {
	ret := _m.Called(ctx, tourismName, locationName, activityName)

	var r0 []tourismpackages.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []tourismpackages.Domain); ok {
		r0 = rf(ctx, tourismName, locationName, activityName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tourismpackages.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, tourismName, locationName, activityName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, locationId
func (_m *Usecase) GetByID(ctx context.Context, locationId int) (tourismpackages.Domain, error) {
	ret := _m.Called(ctx, locationId)

	var r0 tourismpackages.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) tourismpackages.Domain); ok {
		r0 = rf(ctx, locationId)
	} else {
		r0 = ret.Get(0).(tourismpackages.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, locationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, tourismPackagesDomain
func (_m *Usecase) Store(ctx context.Context, tourismPackagesDomain *tourismpackages.Domain) (tourismpackages.Domain, error) {
	ret := _m.Called(ctx, tourismPackagesDomain)

	var r0 tourismpackages.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *tourismpackages.Domain) tourismpackages.Domain); ok {
		r0 = rf(ctx, tourismPackagesDomain)
	} else {
		r0 = ret.Get(0).(tourismpackages.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *tourismpackages.Domain) error); ok {
		r1 = rf(ctx, tourismPackagesDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
