// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"
	activities "erdmaze/businesses/activities"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *Usecase) GetAll(ctx context.Context) ([]activities.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []activities.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []activities.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]activities.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, activityId
func (_m *Usecase) GetByID(ctx context.Context, activityId int) (activities.Domain, error) {
	ret := _m.Called(ctx, activityId)

	var r0 activities.Domain
	if rf, ok := ret.Get(0).(func(context.Context, int) activities.Domain); ok {
		r0 = rf(ctx, activityId)
	} else {
		r0 = ret.Get(0).(activities.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, activityId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, activityDomain
func (_m *Usecase) Store(ctx context.Context, activityDomain *activities.Domain) (activities.Domain, error) {
	ret := _m.Called(ctx, activityDomain)

	var r0 activities.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *activities.Domain) activities.Domain); ok {
		r0 = rf(ctx, activityDomain)
	} else {
		r0 = ret.Get(0).(activities.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *activities.Domain) error); ok {
		r1 = rf(ctx, activityDomain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
